name: pokedex
description: A new Flutter application.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  async_redux: ^24.2.2
  http: ^1.3.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pokemonTypes/
